### ISSUE TITLE
Doesn't play well with ranges including `T::MAX`

### ISSUE THREAD

**Issue by geophree** [spearman/range-set#14]
I think this is related to adding `T::one()` to the range bounds.  Conceivably, the start and/or end of a range could be `T::MAX`, so you shouldn't assume you can add to them without overflow.
```rust
let mut rs = range_set![];
rs.insert_range(0..=u32::MAX); // works
rs.insert_range(0..=0); // panics
```
Also:
```rust
let mut rs = range_set![];
rs.insert_range(0..=0); // works
rs.insert_range(0..=u32::MAX); // panics
```
`T::MAX-1` works fine:
```rust
let mut rs = range_set![];
rs.insert_range(0..=0);
rs.insert_range(0..=(u32::MAX-1)); // works
rs.insert_range(0..=(u32::MAX-1)); // works
```

This came up while I was solving Day 6 part 2 of Advent of Code 2023.  I fixed it by bumping from `u32` to `u64`, but that's an inelegant workaround. Thanks for the great library though!

**Comment by spearman** [comment]
Thanks for reporting. Fixed in [0.0.11](https://github.com/spearman/range-set/commit/ec4b61b1ac1067ce39955b27fb802c728832a648) by replacing some additions with saturating_add.
