### ISSUE TITLE
How to iterate over the ranges, not the elements?

### ISSUE THREAD

**Issue by drauschenbach** [spearman/range-set#6]
I want to create a custom format for my range set, such as `1:5,7,13:21`. I can see how to get an iterator over individual elements, but I don't see how to iterate over ranges.

**Comment by spearman** [comment]
You're right it wasn't possible to access the ranges directly. I've published [version 0.0.8](https://crates.io/crates/range-set/0.0.8) that implements `AsRef<SmallVec>` so that you can use the smallvec iterator:
```
for r in s.as_ref().iter() {
  ...
}
```

**Comment by drauschenbach** [comment]
Works great - thanks!
